### ISSUE TITLE
Sublime Text is not showing in app store

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.sublimetext.three#1]
Sublime Text is not showing on Flathub.org app store or GNOME Software. It looks like that its AppStream metadata are missing or broken.

**Comment by ptomato** [comment]
@nedrichards Any idea? The metadata seems to have built OK. https://flathub.org/builds/#/builders/9/builds/954

**Comment by matthiasclasen** [comment]
Looks to me like the appstream data is missing an icon ?

**Comment by matthiasclasen** [comment]
I just confirmed that manually adding 

    <icon type="cached" height="64" width="64">com.sublimetext.three.png</icon>
    <icon type="cached" height="64" width="128">com.sublimetext.three.png</icon>

to ~/.local/share/flatpak/appstream/flathub/x86_64/active/appstream.xml
on my system makes sublime show up as an installed app in gnome-software.

**Comment by nedrichards** [comment]
We'll add a remote icon in the appdata

**Comment by nedrichards** [comment]
Should be fixed in https://github.com/flathub/com.sublimetext.three/commit/92cb65de4d4f27672c18b1ed5cfb99503caf2c66

**Comment by TingPing** [comment]
@nedrichards We didn't need a remote icon as the icons are in the installed package.

**Comment by RoyiAvital** [comment]
Could you please add [Sublime Merge](https://www.sublimemerge.com/) as well?

**Comment by TingPing** [comment]
@RoyiAvital Stop spamming random issue with package requests.

**Comment by RoyiAvital** [comment]
@TingPing , I think this is the first post of mine in this repository.
Moreover, Where would you like users to express it?

**Comment by TingPing** [comment]
>  I think this is the first post of mine in this repository.

Yea you commented on other repos...

> Moreover, Where would you like users to express it?

Ask the upstream developers to package it. Point them to http://docs.flatpak.org

**Comment by RoyiAvital** [comment]
@TingPing , I also raised request in the Sublime Merge forum.
Yet it seems all packages in Flathub are done by 3rd parties.

For instance, this project isn't supported by Sublime, right?

**Comment by TingPing** [comment]
> Yet it seems all packages in Flathub are done by 3rd parties.

Not all, but quite a few including this one yes. We don't want that in the long term.

**Comment by RoyiAvital** [comment]
As a user who really enjoys Flatpak and believe in the idea I try to request it from any software supplier which I use its products.

Sorry for the noise, just really enjoys this Flatpak and wanted Sublime Merge as well.

Thank You.
