### ISSUE TITLE
Sublime Text application cannot be found within "Open with other application" list in Gnome

### ISSUE THREAD

**Issue by vanessa-chang** [flathub/com.sublimetext.three#16]
### Description
Sublime Text application cannot be found within "Open with other application" list in Gnome

** It works with version 3.2.2 // Build 3211 // Flatpak Date 2019-10-01 (see Excepted behavior session)

### Steps to reproduce
1. Install EOS and boot into OS
2. Right-click on an html file --> Select "Open with Other Application"--> Click "View All Applications" if sublime text is not shown on the list
3. Check if "Sublime Text" application can be searched and selected

### Expected behavior
Sublime Text application can be searched within "Open with Other Application" option
![ok](https://user-images.githubusercontent.com/31236978/77417835-f0f70f80-6e00-11ea-9c85-c674c18d22a4.png)

### Actual behavior
Sublime Text Application cannot be found within "Open with other Application" option
![na](https://user-images.githubusercontent.com/31236978/77417855-feac9500-6e00-11ea-8722-f46a37ec3944.png)

### Environment
Build: Version 3.2.2 / build 3211 / Flatpak date 2020-03-16
Operating system and version: Endless OS 3.7.8
[Linux] Desktop Environment and/or Window Manager: Gnome 3.34

**Comment by ptomato** [comment]
I see the same here! Does anyone know how the list of "related applications" is calculated?

**Comment by rdab** [comment]
@ptomato In the `.desktop` file, add `%F` at the end of the `Exec` line:
```
Exec=/usr/bin/flatpak run ... --command=subl com.sublimetext.three %F
```
