### ISSUE TITLE
The mouse in the word processor does not work

### ISSUE THREAD

**Issue by Gandalf888** [flathub/com.sublimetext.three#2]
**Expected behavior**
After opening the application and entering the text to the editor should be able to navigate the mouse.
...

**Actual behavior**
After starting the application and entering text in the editor window, you can not use the mouse. The application interface works, you can click on the File, Edit ... buttons but you can not use the mouse to select the entered text. The program behaves as if the place where the file is edited was blocked for the mouse. This is only for the flatpak version. The deb version works fine.
...

**Steps to reproduce**
1. Install Sublime Text from Flatpak.
2. Run apps and enter any text.
3. Try, for example, to mark the entered text with the mouse.

**Environment**

> Operating system and version:
> Distributor ID: neon
> Description:    KDE neon User Edition 5.13
> Release:        16.04
> Codename:       xenial

**Monitor:**

Resolution - 1366x768
dpi_scale used in ST - default
Sublime Text:
Sublime Text, version 3.1.1, build 3176, flatpak version

**Comment by ptomato** [comment]
Very strange, I'm definitely not seeing this.
Is there any output when you run it from the terminal?

**Comment by Gandalf888** [comment]
The result of running the application with the flag --verbose

```
user@WorkServer:~$ flatpak run --verbose com.sublimetext.three/x86_64/stable
F: Opening user flatpak installation at path /home/pawelpieczyrak/.local/share/flatpak
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/pawelpieczyrak/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 1268571300
F: Allocated instance id 3127453794
F: Allowing host-fs access
F: Allowing x11 access
F: Running '/usr/lib/flatpak/flatpak-bwrap --args 20 /usr/lib/flatpak/flatpak-dbus-proxy --args=22'
F: Running '/usr/lib/flatpak/flatpak-bwrap --args 16 sublime'
```

Result command flatpak info

```
user@WorkServer:~$ flatpak info com.sublimetext.three/x86_64/stable
Odniesienie: app/com.sublimetext.three/x86_64/stable
Identyfikator: com.sublimetext.three
Architektura: x86_64
Gałąź: stable
Pochodzenie: flathub
Collection ID: 
Data: 2018-06-04 10:44:30 +0000
Temat: Add remote icons for visibility in software stores (92cb65de)
Zatwierdzenie: d6f825fde3257cacc018431b58ad2ea80e79ddf2812654c1c588b654e28a7b5d
Element nadrzędny: bfeda6629cdaeb1486771297d141668c2562afd31431390411baaea86adac186
Położenie: /var/lib/flatpak/app/com.sublimetext.three/x86_64/stable/d6f825fde3257cacc018431b58ad2ea80e79ddf2812654c1c588b654e28a7b5d
Rozmiar po instalacji: 43,4 MB
Środowisko wykonawcze: org.freedesktop.Sdk/x86_64/1.6
Sdk: org.freedesktop.Sdk/x86_64/1.6
```
In the second result there are Polish words, because I have a system in Polish, I'm sorry. If you need to run the program with other commands, enter them and I will do it. I also tested it on Manjaro KDE and on Linux Mint Cinnamon and the problem is the same.

**Comment by DavidLuptak** [comment]
I am also affected by this issue!

I can provide my `flatpak info` output in English:

```
$ flatpak info com.sublimetext.three
Ref: app/com.sublimetext.three/x86_64/stable
ID: com.sublimetext.three
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2018-06-04 10:44:30 +0000
Subject: Add remote icons for visibility in software stores (92cb65de)
Commit: cadaa43d45f1d0d1f39a41760421d21c7b090857ad4fd9dfd50583d91b436db8
Parent: d6f825fde3257cacc018431b58ad2ea80e79ddf2812654c1c588b654e28a7b5d
Location: /var/lib/flatpak/app/com.sublimetext.three/x86_64/stable/cadaa43d45f1d0d1f39a41760421d21c7b090857ad4fd9dfd50583d91b436db8
Installed size: 43,4 MB
Runtime: org.freedesktop.Sdk/x86_64/1.6
Sdk: org.freedesktop.Sdk/x86_64/1.6
```

My environment is:

Ubuntu 18.04 LTS
GNOME 3.28.1
```
$ uname -a
Linux hostname 4.15.0-24-generic #26-Ubuntu SMP Wed Jun 13 08:44:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ptomato** [comment]
I'm completely stumped by this, sorry.

The only possible lead I can think of is that for me, occasionally, scroll events stop working in the editor (i.e. you can only scroll using the scrollbar, not the touchpad or mouse wheel) and then later they start working again. I have no idea if that is related, and I also have no idea how to investigate it.

**Comment by wnklmnn** [comment]
I have the same issue. The mouse works fine in every part of the program except the main editor. I can even scroll through the file using the mouse but the click events don't seem to be registered.

flatpak info com.sublimetext.three
`app/com.sublimetext.three/x86_64/stable flathub cadaa43d45f1d0d1f39a41760421d21c7b090857ad4fd9dfd50583d91b436db8`

uname -a
`Linux pascal-laptop 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux`


If I run the sublime_text executable `.local/share/flatpak/app/com.sublimetext.three/current/active/files/extra/opt/sublime_text/sublime_text` the editor is working fine.

**Comment by fpohtmeh** [comment]
Mouse still doesn't work. OS: Linux Mint 19 Cinnamon

**Comment by ptomato** [comment]
@wnklmnn Thanks for the update. Unfortunately I didn't receive a notification for it, though, and only saw it when reading yesterday's comment. I think adding `LC_NUMERIC=C` to the Flatpak environment in the manifest should work, in that case. I will assign myself to this issue and fix it at some point, but if someone else wants to send a pull request I will be happy to merge it.

**Comment by ryanpcmcquen** [comment]
Any brave souls here willing to test for this issue on Sublime Text 4?
```
flatpak install --user https://dl.flathub.org/build-repo/76704/com.sublimehq.SublimeText.flatpakref
```
