### ISSUE TITLE
 Error with "Wrong size for extra data" on Amd64

### ISSUE THREAD

**Issue by adrianteri** [flathub/com.sublimetext.three#20]
I have a similar issue to this [Minecraft's](https://github.com/flathub/com.mojang.Minecraft/issues/33) FlatHub repo. 

![Screenshot from 2020-10-01 03-22-02](https://user-images.githubusercontent.com/10687877/94753038-acdb5d80-0395-11eb-8547-a42d632be3c6.png)

**Comment by FilBot3** [comment]
I am also getting this error when attempting to install on Pop!_OS/Ubuntu

```
➜  ~ flatpak --user install com.sublimetext.three
Looking for matches…
Found similar ref(s) for ‘com.sublimetext.three’ in remote ‘flathub’ (user).
Use this remote? [Y/n]: y

com.sublimetext.three permissions:
    ipc     network     fallback-x11     wayland     x11     dri     file access [1]     dbus access [2]

    [1] host
    [2] org.gnome.SettingsDaemon


        ID                             Branch          Op          Remote          Download
 1. [✗] com.sublimetext.three          stable          i           flathub         10.3 MB / 10.2 MB

Error: Wrong size for extra data http://packagecontrol.io/Package%20Control.sublime-package
error: Failed to install com.sublimetext.three: Wrong size for extra data http://packagecontrol.io/Package%20Control.sublime-package
```

![image](https://user-images.githubusercontent.com/3039509/94811396-ed999d80-03ba-11eb-936a-dfbfdb00c869.png)

**Comment by ptomato** [comment]
It seems that Package Control released a new version 3.4.0 a few days ago, and quietly replaced the existing file in the download location... so this is working as intended, "protecting" your system from a potentially malicious file with unexpected contents! :joy:

I can update the signature, but I wonder if we can instead get away with not pre-installing Package Control at all, now that Sublime Text has an actual in-app install process for Package Control?

**Comment by FilBot3** [comment]
I don't have an issue with removing Package Control. Would that update the Flatpak itself once installed and would it persist or would it reset everytime you open the editor?

**Comment by ptomato** [comment]
I'd have to test it, but I expect that Package Control would be gone the next time you opened the app after upgrading it from Flathub, and then once you reinstalled Package Control via the menu item, it would remain installed thereafter.

(Maybe it's not such a good idea after all to make an upgrade that silently uninstalls Package Control, though.)
