### ISSUE TITLE
How to use subl command?

### ISSUE THREAD

**Issue by asch75** [flathub/com.sublimetext.three#24]
Hi guys, need some help.

How can I use the subl command, (available in Sublime Text), through terminal?

Thanks.

**Comment by ptomato** [comment]
I have `alias subl='flatpak run com.sublimetext.three'` in my `~/.bashrc` file.

**Comment by Jmennius** [comment]
Alternatively, you can create a symbolic link to flatpak exports like so `ln -s /var/lib/flatpak/exports/bin/com.sublimetext.three /usr/local/bin/subl`.
This is shell agnostic.

P.S. should this be closed?
