### ISSUE TITLE
TypeScript plugin needs node in flatpak sandbox, and thus does not work

### ISSUE THREAD

**Issue by Fulguritude** [flathub/com.sublimetext.three#25]
Redirected here from: https://github.com/pop-os/pop/issues/1478

In a nutshell, I have the flatpak version of ST3 downloaded from the Pop! Shop. The Microsoft TypeScript Plugin for ST3 needs access to nodejs to run, but the node executable does not exist in the sandbox.

I have also tried downloading the node SDK extension for flatpak from the Pop! Shop, as a possible way to add node to the sandbox, but this does not seem to work either; and node still isn't present in the sandbox. 

Is there a way to add the binary I want to the flatpak sandbox ? Or is it some issue on your end, where you need the flatpak wrappers over ST3 to call some flatpak-specific command that allows the sandbox to get node from the host system ?

Thanks for your help.

**Comment by Fulguritude** [comment]
I solved the issue following this ST3 install procedure, https://www.sublimetext.com/docs/3/linux_repositories.html

I'm sorry I couldn't find a solution using your flatpak executable. Hope you get this fixed in any case. Thanks !

**Comment by ptomato** [comment]
We have [com.sublimetext.three.DevUtils](https://github.com/flathub/com.sublimetext.three.DevUtils) containing dependencies for common plugins for this purpose. In gnome-software it's available to install as an add-on along with Sublime Text. Maybe you could file a bug with the Pop app store asking them to make the add-on more prominent?
